# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/huawei/prague/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/huawei/prague

PRODUCT_COPY_FILES += \
    vendor/huawei/prague/proprietary/odm/etc/audio/algorithm/algorithm_PRAGUE_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/algorithm/algorithm_PRAGUE_normal.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/dts/dts_PRAGUE_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/dts/dts_PRAGUE_normal.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/hissc/mixer_paths_PRAGUE.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_paths_PRAGUE.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/hissc/mixer_volumes_PRAGUE_ce.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_PRAGUE_ce.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/hissc/mixer_volumes_PRAGUE_cmcciot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_PRAGUE_cmcciot.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/hissc/mixer_volumes_PRAGUE_gcf.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_PRAGUE_gcf.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/hissc/mixer_volumes_PRAGUE_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_PRAGUE_normal.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/hissc/mixer_volumes_PRAGUE_telecomiot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_PRAGUE_telecomiot.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/hissc/mixer_volumes_PRAGUE_unicomiot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_PRAGUE_unicomiot.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/hissc/pop_seq_PRAGUE.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/pop_seq_PRAGUE.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/mbdrc/mbdrc_PRAGUE_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/mbdrc/mbdrc_PRAGUE_normal.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/modem/modem_PRAGUE_cmcciot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_PRAGUE_cmcciot.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/modem/modem_PRAGUE_gcf.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_PRAGUE_gcf.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/modem/modem_PRAGUE_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_PRAGUE_normal.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/modem/modem_PRAGUE_telecomiot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_PRAGUE_telecomiot.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/modem/modem_PRAGUE_unicomiot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_PRAGUE_unicomiot.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/sws/sws_PRAGUE_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_PRAGUE_normal.xml \
    vendor/huawei/prague/proprietary/odm/etc/audio/sws/sws_config.txt:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_config.txt \
    vendor/huawei/prague/proprietary/odm/firmware/ts/prague_CYTT21403_default.bin:$(TARGET_COPY_OUT_ODM)/firmware/ts/prague_CYTT21403_default.bin \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.HI843_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.HI843_OFILM.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX219_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX219_LITEON.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX219_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX219_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX386E3_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX386E3_OFILM.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX386E3_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX386E3_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX486_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX486_OFILM.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX486_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.IMX486_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV12870E3_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV12870E3_LITEON.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV12A10_FOXCONN.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV12A10_FOXCONN.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV12A10_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV12A10_LITEON.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV12A10_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV12A10_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV8856_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.p.OV8856_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.HI843_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.HI843_OFILM.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX219_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX219_LITEON.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX219_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX219_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX386E3_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX386E3_OFILM.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX386E3_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX386E3_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX486_OFILM.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX486_OFILM.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX486_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.IMX486_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV12870E3_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV12870E3_LITEON.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV12A10_FOXCONN.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV12A10_FOXCONN.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV12A10_LITEON.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV12A10_LITEON.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV12A10_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV12A10_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV8856_SUNNY.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.PRAGUE.s.OV8856_SUNNY.so \
    vendor/huawei/prague/proprietary/odm/lib64/hwcam/hwcam.hi6250.m.PRAGUE.so:$(TARGET_COPY_OUT_ODM)/lib64/hwcam/hwcam.hi6250.m.PRAGUE.so \
    vendor/huawei/prague/proprietary/vendor/etc/libnfc-brcm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-brcm.conf \
    vendor/huawei/prague/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/huawei/prague/proprietary/vendor/lib64/libpn551_fw.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpn551_fw.so
